### PR TITLE
Add CodeTriage.com (from Boston) in Resources.md.

### PR DESCRIPTION
**Pull request by AnneTheAgile**
You all have such a great resources page, thank you! I just told a New Yorker who is going to teach AP Computer Science to High Schoolers this year [1]. I realized you were missing one of my all time favorite sites, CodeTriage [2]! 

[1] Blogger solicits ideas for teaching. http://www.kchodorow.com/blog/2014/07/15/sharing-programming/
[2] In vein of 24-pull requests, but even simpler: find projects with lots of open tickets and comment on them to move them forward. Naturally, PR's welcome too, but I have found that reading code this way is really helpful and warms one up to doing a PR.  http://www.codetriage.com/

### CODE REVIEW

**Comment by AnneTheAgile** [comment]
I got this funny auto-responder? 
 From: GitHub noreply@github.com [Add to Address Book]
To: AnneTheAgile annemoroney@alum.mit.edu
Subject: [hackerhours.org] Page build warning
Date: Oct 7, 2014 2:29 PM

The page build completed successfully, but returned the following warning:

CNAME already taken: hackerhours.org

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions please contact us at https://github.com/contact.

**Comment by afeld** [comment]
> You all have such a great resources page, thank you! 

high five

> I just told a New Yorker who is going to teach AP Computer Science to High Schoolers this year

Great! Yeah, I would love for teachers to see it as an alternative/supplement to office hours.

> I realized you were missing one of my all time favorite sites, CodeTriage!

Umm, it was in the list already :wink:

**Comment by afeld** [comment]
> I got this funny auto-responder?

Weird. I would think the CNAME would be ignored from a fork.

**Comment by afeld** [comment]
... in other words, don't worry about it.

**Pull request closed without merging**
