### PR TITLE
A potential logo implementation

### PR DESCRIPTION
**Pull request by jeremiak**
We made a logo #25 during the open source hack day and I thought I'd take a stab at working it into the page.

What do you all think? I put up the current branch at [http://jeremiak.github.io/hackerhours.org/](http://jeremiak.github.io/hackerhours.org/) to check out

### CODE REVIEW

**Comment by afeld** [comment]
Nice! What do you think about having it replace the first "H", or moving the logo centered above the title?

**Comment by jeremiak** [comment]
Interesting ideas, I gave them both a shot
1. I think replacing the first "H" makes it look kind of corny, but open to it: http://up.jeremiak.com/amsp
2. Centering the logo on a new line could work: http://up.jeremiak.com/an0G

I personally like them both on the same line but I'm not committed to any of the layouts. What do you think @SiberianCharm?

**Comment by afeld** [comment]
> I think replacing the first "H" makes it look kind of corny

It would probably need to more closely match the font to work inline. We could just move the logo to the top left corner and not ever put it next to the full title...

**Comment by jeremiak** [comment]
So matching the font a bit more makes it look pretty cool, imho: http://up.jeremiak.com/an4t.

I think it might be better to use it like this than in the navbar because I think it will be a bit too small to see. But I'll go ahead and give it a shot in a bit.

**Comment by afeld** [comment]
> matching the font a bit more makes it look pretty cool

Works for me! May continue to play with the proportions/kerning, but I think this could be close.

> I think it will be a bit too small to see

I'm not attached to the current layout of the navbar (or the site in general), but that's a whole other can of worms :wink:

**Comment by gabekneisley** [comment]
screen shot 2015-04-27 at 12 18 21 pm
What if we change the font to something with a similar stroke width to character width ratio, so that the logo fits more naturally. How about [Roboto](http://www.google.com/fonts/specimen/Roboto) maybe 700 or 900.

**Comment by jeremiak** [comment]
@gabekneisley I think that's an awesome idea, here it is with Roboto: http://up.jeremiak.com/an4k

The problem is getting it to work well on mobile: http://up.jeremiak.com/an6Z

I'm going to go back to playing around with having the logo centered. Maybe if it on a line under the `h1` text it will look a bit more in place

**Comment by gabekneisley** [comment]
One other idea could be to actually use the **H** from the font, with the font-size set to a pixel value. Keep the clockface part of the logo, and position it absolutely onto the text itself, like so:

[CodePen](http://codepen.io/anon/pen/MwYQRa), but missing your clever positioning calculations :)
screen shot 2015-04-27 at 4 22 47 pm

**Comment by emiclark** [comment]
I like the idea of using the font as a base and juxtaposing the clock face on top. Don't know if the logo would behave consistently over all devices. Worse case scenario is that you will have a floating clock face and the HackerHours will stay intact.
The extra heavy bold font above feels very weighted, heavy, & serious. Maybe a lighter font will convey social, communal, helping & sharing. Thought that a two toned treatment may be nice.
hackerhours-logodesign

**Comment by afeld** [comment]
> Don't know if the logo would behave consistently over all devices

I say we decide on the ideal, and we'll figure out how to make it work.

> a lighter font will convey social, communal, helping & sharing

:+1:

**Comment by afeld** [comment]
@kbaum Whaddya think?

**Comment by kbaum** [comment]
Disclaimer.. i suck at design.

Looks awesome already... love the clock and i love that we use javascript to animate the logo because that gives it more of who we are.

One thought.. Could we try putting the Hours underneath the Hacker?  Also, we could try being a little bit more edgy and using one leading H for both Hacker and Hours.  This will also make it a little more self contained and DRY :smile:

**Comment by emiclark** [comment]
Here's a quick and dirty draft of the logo, going in a different direction. The font is Noteworthy. I got this idea by looking around the office and seeing writing on the walls, desks, any possible surface available. The clock is a play on the o in hours. It's cute, relaxed
hackerhours-logodesign2
. Don't really know if that is what you are going for.

**Comment by afeld** [comment]
Nice! Certainly more fun, and I like that has a feel of whiteboarding. The one thing I like about the clock in the "H" is that it's square-ish so it works as an avatar, e.g. for the Meetup page and Twitter.

hacker_hours__new_york__ny__-_meetup

I suppose we could just use it in the banner and figure out something else for the avatar...

**Comment by emiclark** [comment]
I like the red in thoughtbot's robot logo. Also like anything alien, robot, and cute like githubs' logo. Made a version where the words stack ontop of each other.
hhclock

The abstract idea of time flies when hacking at hacker hours.... maybe reaching too far on this ...

**Comment by afeld** [comment]
Haha yeah I think the clock _plus_ the wings are a bit much. Thanks for playing with it though!

**Comment by afeld** [comment]
Closing in favor of #160. Thanks for all the work on this!

**Pull request closed without merging**
