### PR TITLE
Create aadeschamps.yml

### PR DESCRIPTION
**Pull request by aadeschamps**

### CODE REVIEW

**Comment by afeld** [comment]
In under the wire – see you soon!

**Comment by aadeschamps** [comment]
Hi,

I'm actually coming in from long osland , I might be a little bit late. Is
that alright? I know the page on meetup said you wanted people on time.

Thanks,
Alex Deschamps

**Comment by afeld** [comment]
We'll make it work. Thanks!

**Comment by aadeschamps** [comment]
Hey,

Sorry I did not make it in the end. I decided to drive in thinking that it
would get me there earlier. I've driven in on a Sunday before and I thought
it wouldn't be too bad. I guess there was some kind of walk going on, and
it ended up taking almost 3 hours to make my way downtown. I then couldnt
find any parking and I figured it was too late. Its unfortunate because I
was actually taught how to program by someone who was very enthusiastic
about open source projects and contributing to them and I would love to get
involved but simply don't know how. Ill definitely sign up (and make it)
the next time you do something like this.

Sorry again,
Alex Deschamps

**Pull request merged**
